### PR TITLE
Support transaction

### LINKED ISSUE #20: Minimal example with Transaction?
Hello,
I'm trying to make a transaction, but I am hitting a wall and can't figure it out.

Is it possible for an example with transaction and 2 inserts for example?

### PR DESCRIPTION
**Pull request by elpiel**
Currently the `fn transaction()` was created for the postgres implementation as per https://github.com/khuey/bb8/issues/20#issuecomment-492384355 .
We can implement the same thing for Redis and add a transaction fn in `bb8` that will call the specific connection `transaction()` fn I guess?

Resolves #20 

@khuey I couldn't get the `E: From<tokio_postgres::Error>` working sadly.
```
error[E0271]: type mismatch resolving `<Fut as futures::IntoFuture>::Error == (tokio_postgres::Error, tokio_postgres::Client)`
   --> postgres/src/lib.rs:104:10
    |
104 |         .and_then(|connection| f(connection))
    |          ^^^^^^^^ expected type parameter, found struct `tokio_postgres::Error`
    |
    = note: expected type `(E, tokio_postgres::Client)`
               found type `(tokio_postgres::Error, tokio_postgres::Client)`

```

### CODE REVIEW

**Comment by khuey** [comment]
Something like this works.

```diff
diff --git a/postgres/src/lib.rs b/postgres/src/lib.rs
index 87c38ce..47bd6a7 100644
--- a/postgres/src/lib.rs
+++ b/postgres/src/lib.rs
@@ -90,16 +90,20 @@ where
 }

 /// Run asynchronous into a Transaction
-pub fn transaction<R, Fut, F>(mut connection: tokio_postgres::Client, f: F) -> impl Future<Item=(R, tokio_postgres::Client), Error=(tokio_postgres::Error, tokio_postgres::Client)>
+pub fn transaction<R, E, Fut, F>(mut connection: tokio_postgres::Client, f: F) -> impl Future<Item=(R, tokio_postgres::Client), Error=(E, tokio_postgres::Client)>
     where
         F: FnOnce(tokio_postgres::Client) -> Fut,
-        Fut: Future<Item=(R, tokio_postgres::Client), Error=(tokio_postgres::Error, tokio_postgres::Client)>,
+        E: From<tokio_postgres::Error>,
+        Fut: Future<Item=(R, tokio_postgres::Client), Error=(E, tokio_postgres::Client)>,
 {
     connection.simple_query("BEGIN")
         .for_each(|_| Ok(()))
         .then(|r| match r {
             Ok(_) => Ok(connection),
-            Err(e) => Err((e, connection)),
+            Err(e) => {
+                let error: E = e.into();
+                Err((error, connection))
+            },
         })
         .and_then(|connection| f(connection))
         .and_then(|(result, mut connection)| {
@@ -107,11 +111,11 @@ pub fn transaction<R, Fut, F>(mut connection: tokio_postgres::Client, f: F) -> i
                 .for_each(|_| Ok(()))
                 .then(|r| match r {
                     Ok(_) => Ok((result, connection)),
-                    Err(e) => Err((e, connection))
+                    Err(e) => Err((e.into(), connection))
                 })
         })
         .or_else(|(e, mut connection)| {
             connection.simple_query("ROLLBACK").for_each(|_| Ok(()))
-                .then(|_| Err((e, connection)))
+                .then(|_| Err((e.into(), connection)))
         })
-}
\ No newline at end of file
+}
```

**Comment by elpiel** [comment]
@khuey thanks for the help, from here on, what's next?
Adding the method to `ManageConnection`?

**Comment by djc** [comment]
@elpiel are you still interested in finishing this?

**Comment by elpiel** [comment]
Yes, I am. I would love to continue on this once the #45 is merged.

**Comment by godofdream** [comment]
@elpiel looks like #45 is merged.

**Comment by djc** [comment]
Going to close this for lack of progress. Feel free to reopen (or open a new one) if someone wants to work on this.

**Pull request closed without merging**
